# Generated by Django 5.0.1 on 2024-01-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='key',
            field=models.TextField(),
        ),
    ]
